### ISSUE TITLE
Parameter swisssearch does not perform search

### ISSUE THREAD

**Issue by ninaDeimos** [geoadmin/web-mapviewer#1043]
Since the commit https://github.com/geoadmin/web-mapviewer/commit/d28d0ba3f91f419fcba2c6897e5d18f8a9b4c12b, the parameter swisssearch no longer performs the search but only fills the search input field.
This is quite inconvenient for a direct map link parameter that should show a search result.

**Comment by pakb** [comment]
#1084 should fix this issue
It now will search for any `swisssearch` param that was given at startup, and then proceed as normal. That means that further change on the `swisssearch` (after app init) won't do anything, and the search bar is now disconnected from the param (like it was before on the old viewer)

This will be deployed with the next release
