### ISSUE TITLE
Error in displaying GetFeatureInfo Content

### ISSUE THREAD

**Issue by maxcollombin** [geoadmin/web-mapviewer#1103]
## Description

An error occurs when trying to display the content of a `GetFeatureInfo` request on the map viewer.
The following error message is thrown : `Plain text parsing not implemented`.

This error originates from the script: [utils-DMgTHRVL.js](https://map.geo.admin.ch/v1.47.1/assets/utils-DMgTHRVL.js), preventing the proper display of the request content in the map viewer.

## Expected Behavior

The content of the `GetFeatureInfo` request should be displayed in an HTML pop-up window when a feature is clicked on the map.

## Steps to Reproduce

1. Folow the link: https://s.geo.admin.ch/7ohrzlwvuesq
2. Click on one of the features on the map to trigger a `GetFeatureInfo` request

## Additional Information

The response from the `GetFeatureInfo` request is received successfully, as shown in the screenshot below:

![GetFeatureInfoMapGeoAdminResponse](https://github.com/user-attachments/assets/1cb4c024-0811-4de8-861c-f33e556cb5f4)

**Comment by ismailsunni** [comment]
hi @maxcollombin I have fixed the issue in this PR https://github.com/geoadmin/web-mapviewer/pull/1074 but we haven't deployed the fix in production. If you want to check it, you can check the develop instance: https://sys-map.dev.bgdi.ch/

**Comment by pakb** [comment]
fix is now online on map.geo.admin.ch
