### ISSUE TITLE
Fullscreen switch mobile :expected workflow

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/web-mapviewer#15]
OS: iphone
Browsers: all

reproduce:
open http://web-mapviewer.dev.bgdi.ch/ltbtp_add_header_and_search/index.html 

pan and zoom: fullscreen and as soon the touch event is gone:  elements come back

expected behaviour

as in swisstopo app

tap: fullscreen
tap: fullscreen stoped, elements back 
(see eg https://photos.app.goo.gl/711Dcu8TDybDkPVW8 )

**Comment by pakb** [comment]
do you mean the fact the menu bar will go up hiding when we drag the map?

**Comment by davidoesch** [comment]
No - I mean : single tap does a fullscreen. When in full screen: tap goes Back in normal mode as in https://apps.apple.com/ch/app/swisstopo/id1505986543

When dragging : for the User there is too much distraction with the ob and off of the bar. Too much distraction and unrest.

**Comment by pakb** [comment]
Ok, yeah sounds good. But this would be available only on smaller devices right? (aka to the tablet size with touch, but not beyond to desktop?)
To identify under the touch, double touch? Or single touch identifies and toggle this full screen mode?

**Comment by davidoesch** [comment]
Devices: Only on mobile / touch devices 
Touch: a Single touch on the background map (touch on a feature opens object info,Double touch is Zoom in, Touch n hold is the position info)
Rapid touch?

**Comment by pakb** [comment]
There's a first implementation of that on DEV now : http://web-mapviewer.dev.bgdi.ch/
What I did is that I wait after a click (250ms) to see if the user will double click or not, if single click then I switch to full screen. Otherwise double click is handled as usual (zoom on map)

**Comment by pakb** [comment]
further work will be done here : https://jira.swisstopo.ch/browse/BGDIINF_SB-2235
let's keep issues on GitHub for external reporting
