### ISSUE TITLE
iOS: Save to home screen does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/web-mapviewer#16]
os: iphone ios14
browser:safari

open http://web-mapviewer.dev.bgdi.ch/ltbtp_add_header_and_search/index.html  or http://web-mapviewer.dev.bgdi.ch/

save to home screen

start link from home screen

result:
error "No such key .."

expected result:
application starts

**Comment by pakb** [comment]
will be done through https://jira.swisstopo.ch/browse/BGDIINF_SB-2241
let's keep anything internal on JIRA and use GitHub issue to interact with the community.
