### ISSUE TITLE
Add  Warning in header for http://web-mapviewer.dev.bgdi.ch/ http://web-mapviewer.int.bgdi.ch/

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/web-mapviewer#20]
On https://github.com/geoadmin/web-mapviewer we make DEV and INT urls public 
![image](https://user-images.githubusercontent.com/4577727/98245448-3bcd2e00-1f71-11eb-8e85-ab596e432651.png)

in the past, making DEV and INT URL public led to operational use of them, so actually I would suggest to hide them. 
wonder what @gjn and @boecklic 

In any case: add a a header with a warning to it 
as eg in https://mf-geoadmin3.dev.bgdi.ch/index.html?config_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fltfas_sonnenscheindauer%2Fconfigs&api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fltfas_sonnenscheindauer&lang=de&wms_url=%2F%2Fwms-test.dev.bgdi.ch%2Fdev_ltfas_abnahme%2Fxx%2F&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.meteoschweiz.klimanormwerte-sonnenscheindauer_1961_1990,ch.meteoschweiz.klimanormwerte-sonnenscheindauer_aktuelle_periode&wmts_url=%2F%2Fservice-proxywms.dev.bgdi.ch&E=2629162.52&N=1178428.65&zoom=1 

![image](https://user-images.githubusercontent.com/4577727/98245689-99617a80-1f71-11eb-96c2-b3cb4d7939ab.png)

**Comment by fkm** [comment]
First part is in review in #158.

**Comment by pakb** [comment]
For the second part, we already share our work in progress through test linked that leads to our DEV environnement, so anyone interested can easily find them.
Second part will be discussed on our JIRA through this ticket : https://jira.swisstopo.ch/browse/BGDIINF_SB-2240
