### ISSUE TITLE
SSRF Vulnerability in Import Functionality of Master Branch of Application

### ISSUE THREAD

**Issue by n0psn0ps** [geoadmin/web-mapviewer#263]
Hello, I am a security researcher and I was testing your application for various issues. I found that I was able to interact with an external domain with the master branch application found here: https://sys-map.int.bgdi.ch/ 
I thought this was interesting since I could ping out to my own domain and input various files. It appeared that the application was only validating the http:// or https:// scheme and would allow a connection to go through to any domain.
I loaded the Request in Burp Suite an intercepting proxy and tested for various other schemes such as gopher://, ftp://, file:// and found it was giving me errors. So I began appending various IPs with https:// or http:// and I found the AWS internal IP of 169.254.169.254 would return internal data. Screenshot below:

![image](https://user-images.githubusercontent.com/68410650/194631826-71755258-6744-4fee-a0a9-8eb3846e1735.png)

As per this issue it appears that deploying an allow or deny list either by domain and restricting IPs would help resolve this issue for the proxy server. Please see recommended reading and remediation below based on CWE and OWASP top ten.

https://cwe.mitre.org/data/definitions/918.html
https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/

**Comment by davidoesch** [comment]
We really appreciate that you are reaching out to us ...
We take your findings into account. 
The repo is not yet in productive use- so we can tackle your findings.

**Comment by n0psn0ps** [comment]
David, thanks so much for the reply. Would you mind once the patch has been implemented that we assign a CVE to it? Thanks in advance.

**Comment by davidoesch** [comment]
Hi 
It is an implemantion fault on our side. We will remove the proxy based approach completely  in on ou four next dev sprints.

**Comment by n0psn0ps** [comment]
Awesome, can we assign a CVE to this issue? or can this be done on my end?

**Comment by davidoesch** [comment]
@boecklic  you want to asign a CVE?

**Comment by n0psn0ps** [comment]
Also happy to re-assess the issue if you would like. Just to see if the fix has been validated or there is a bypass.

**Comment by n0psn0ps** [comment]
Just circling back around on the CVE assignment. Do we have an estimated timeline when this will be submitted? I can also submit one on my end via MITRE. Just give me the green light and I will begin the process.

**Comment by davidoesch** [comment]
Hi 
Since this repo is only a test system at the time beeing and not used yet on production ( and not yet used by other users) we think it is an overkill to assign a CVE.
in a couple it will be fixed
David
