### ISSUE TITLE
missing print dialog

### ISSUE THREAD

**Issue by nachtswirdesdunkel** [geoadmin/web-mapviewer#371]
on the website https://map.geo.admin.ch i can use the print dialog.
i am not able to find this ability in web-mapviewer.
Am i missing something?

**Comment by pakb** [comment]
that's on purpose, we are not shipping all features done. Otherwise it would take too long before anything goes online
https://www.geo.admin.ch/en/map-viewer/map-viewer.html

So print will come in time, it was not in the scope of our MVP target.

**Comment by nachtswirdesdunkel** [comment]
thanks a lot.
