### ISSUE TITLE
import geoJson

### ISSUE THREAD

**Issue by nachtswirdesdunkel** [geoadmin/web-mapviewer#372]
I have to migrate from the old api to new new one. I am still struggling with the new environment.
Is there a easy way to import a geojson file from a database?
I would realy appreciate a small example function or if it is implementes as url-argument like the kml files. 
example of the database and colors: 
https://geologen.ch/data/
Thanks
Andres

**Comment by pakb** [comment]
I'm not sure I follow what you are trying to achieve, or if you are asking the question at the correct location.
On `mf-geoadmin3` (map.geo.admin.ch) you can add a GeoJSON by going in "Advanced tool / Import / Local".
On this project, we currently do not support external file import (yet?)

**Comment by nachtswirdesdunkel** [comment]
i used the example https://codepen.io/geoadmin/pen/ZWzXgv to render data from the database into the map.
unfortunately everything changed. any hint would be appreciated. 
ie: howto add hardcoded a own geojson source like "Ladestationen"

**Comment by pakb** [comment]
Then you might not have asked on the right project, the codepen you linked is using our outdated JS API, which is linked to the project https://github.com/geoadmin/mf-geoadmin3
I'm sadly unaware how this JS API functions and what parameter are available, so you might have more luck asking your question on the Geoadmin GoogleGroup : https://groups.google.com/g/geoadmin-api

**Comment by nachtswirdesdunkel** [comment]
No, actually i want to use the new web-mapviewer. i found the same functions inside the code of web-mapviewer, but no way to inject own geojson url.

**Comment by pakb** [comment]
there is not support for external GeoJSON through the URL yet, you could get away by forking the project and injecting your GeoJSON configuration into `OpenLayersMap.vue` component, using a `OpenLayersGeoJSONLayer.vue` alongside the other layers coming from the config

**Comment by nachtswirdesdunkel** [comment]
Thanks
i was able to inject my geojsonLayer. Its a hack, but I hope there will be an interface in the future.

**Comment by pakb** [comment]
There will be support for GeoJSON import through the URL in the near future, as there is currently for WMS / WMTS, it's just a matter of time 😉
