### ISSUE TITLE
height profile.json only 2m instead of 0.5m

### ISSUE THREAD

**Issue by nachtswirdesdunkel** [geoadmin/web-mapviewer#384]
is there a way to get the more precise height information of 0.5m instead of 2m from profile.json?
i was not able to find any documentation.
Thanks
Andres

**Comment by pakb** [comment]
our backend service doesn't use 0.5m tiles yet.
You can download the tiles from if you really need to have a better precision quicker than us switching our backend : https://www.swisstopo.admin.ch/en/geodata/height/alti3d.html#download
