### ISSUE TITLE
Broken links in documentaiton

### ISSUE THREAD

**Issue by gmoney1729** [geoadmin/web-mapviewer#707]
Hello,

While going through the documentation, I noticed couple broken links (404). Please see below:

1. https://github.com/geoadmin/doc-guidelines/tree/master/adr (README.md under Architectural decisions)
2. https://github.com/geoadmin/doc-guidelines/blob/master/adr/2020_04_06_next_gen_viewer.md (adr/2020_04_06_javascript_framework_choice.md)

Thanks for looking into it.

**Comment by pakb** [comment]
Hello,
These files have been unfortunately moved to a private repo. I'll raise this issue during our next team meeting, see how we should deal with that (either remove links to private repo, or disclose these files)
