### ISSUE TITLE
Link to https://github.com/geoadmin/doc-guidelines/tree/master/adr broken

### ISSUE THREAD

**Issue by delixfe** [geoadmin/web-mapviewer#74]
You link in the README.md to <https://github.com/geoadmin/doc-guidelines/tree/master/adr>. I get a 404. Maybe this is a private repo.

**Comment by pakb** [comment]
It is yes. Are you interested in any architectural decision we've made so far?

**Comment by delixfe** [comment]
Not really :). I just stumbled over it.
