### ISSUE TITLE
Icon size representing classifications in layer ch.bfs.arealstatistik

### ISSUE THREAD

**Issue by claudiof2023** [geoadmin/web-mapviewer#906]
Hi,

For layer ch.bfs.arealstatistik, the icon size representing the classifications is different between the two versions of the map viewer :

https://map.geo.admin.ch/?topic=ech&zoom=11&layers=ch.bfs.arealstatistik&layers_timestamp=2018&E=2644100.0002&N=1250099.9995&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe

https://test.map.geo.admin.ch/#/map?lang=de&center=2644100,1250100&z=12&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&layers=ch.bfs.arealstatistik@year=2018

It would be nice to have a parameter passed in the URL. Or to decide a  fix value.

Best regards

**Comment by ltshb** [comment]
Thanks for reporting we will look at it.

Internal ticket PB-692

**Comment by hansmannj** [comment]
Hi there,

this should be resolved meanwhile.
If there are still issues, please don't hesitate to come back to us.

Best regards!
